server {
    listen 80;

    location /geoloc/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /geoloc/index.html;
    }

    location /geoloc/api/ {
        proxy_pass http://backend:5010/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /geoloc/uploads/ {
        proxy_pass http://backend:5010/uploads/;
    }
}
